#!/usr/bin/env python3
"""Build dependency-free, indexable Russian and English GitHub Pages pages."""
import json
from hashlib import sha256
from pathlib import Path
from html import escape as esc
from datetime import date
ROOT = Path(__file__).resolve().parents[1]
DOMAIN = 'https://mserdyuk.ru'
LANG = 'ru'
def asset(path): return '/' + path + '?v=' + sha256((ROOT/path).read_bytes()).hexdigest()[:10]
def t(ru, en): return ru if LANG == 'ru' else en
def home(): return '/' if LANG == 'ru' else '/en/'
def case_url(slug): return home() + 'projects/' + slug + '/'
def label(text): return esc(text, quote=True)
def link(url, text, cls='', extra=''): return f'<a href="{url}" class="{cls}" {extra}>{text}</a>'
def cta(text=None): return link('https://t.me/serdukmark', text or t('Написать в Telegram','Message on Telegram'), 'button primary', 'target="_blank" rel="noopener" data-track="telegram_click"')
def cv(): return link('/serdyuk-mark-cv.pdf',t('Резюме PDF ↗','CV PDF · RU ↗'),'text-link','download data-track="cv_download"')
ARROW='<span aria-hidden="true">↗</span>'
CASES=[
 {'slug':'magnit','company':['Магнит Tech','Magnit Tech'],'period':['Июнь 2026 — сейчас','June 2026 — present'],'type':['AI / Внутренние платформы','AI / Internal platforms'],
 'title':['Мультиагентный AI-ассистент в Магнит Tech','Multi-agent AI assistant at Magnit Tech'],
 'short':['Мультиагентный ассистент: поиск информации, расчёты, метрики и управленческая отчётность.','A multi-agent assistant for information retrieval, calculations, metrics and management reporting.'],
 'role':['Продуктовый менеджер','Product Manager'],
 'intro':['Создал и вывел в эксплуатацию корпоративного AI-ассистента. Продуктом еженедельно пользуются более 700 сотрудников на руководящих позициях.','Built and launched a corporate AI assistant, used weekly by more than 700 employees in leadership roles.'],
 'task':['Объединить поиск информации, расчёты, анализ метрик и подготовку отчётности в рабочем инструменте для руководителей.','Bring information retrieval, calculations, metric analysis and reporting into a working tool for leaders.'],
 'actions':[['Создал AI-ассистента на мультиагентной архитектуре и довёл его до эксплуатации.','Built a multi-agent AI assistant and brought it into production.'],['Интегрировал корпоративные модели и AI-агентов для поиска, расчётов и анализа.','Integrated corporate models and AI agents for search, calculations and analysis.'],['Запустил портал обучения и обучил 150+ продактов и тимлидов работе с AI.','Launched a learning portal and trained 150+ product managers and team leads in AI tools.'],['Перезапустил базу знаний с общим дизайн-кодом, личным кабинетом и доступом к внутренним сервисам.','Relaunched the knowledge base with a shared design system, personal workspace and access to internal services.']],
 'metrics':[['700+',['еженедельных пользователей среди руководителей','weekly users in leadership roles']],['100',['млн ₽ экономического эффекта в год','million RUB economic impact per year']],['150+',['продактов и тимлидов обучены AI','PMs and team leads trained in AI']]],
 'closing':['Для меня запуск AI-продукта включает и сам инструмент, и его внедрение: обучение, доступ к знаниям и встраивание в рабочие процессы.','For me, launching an AI product includes both the tool and its adoption: training, access to knowledge and integration into everyday work.'],
 'steps':[['Информация','Information'],['AI-ассистент','AI assistant'],['Рабочая задача','Everyday task']]},
 {'slug':'yandex','company':['Яндекс','Yandex'],'period':['Февраль — июнь 2026','February — June 2026'],'type':['B2C / Запуск с нуля','B2C / Zero to one'],
 'title':['«Грузчик без машины»: запуск сервиса в Яндексе','Launching “Mover without a van” at Yandex'],
 'short':['«Грузчик без машины» — исследование, бизнес-кейс, пользовательский путь и выход в production.','“Mover without a van”: research, business case, user journey and production launch.'],
 'role':['Продуктовый менеджер','Product Manager'],
 'intro':['Запустил сервисный сценарий «Грузчик без машины»: от исследования потребности и бизнес-кейса до тестирования и передачи в промышленную эксплуатацию.','Launched the “Mover without a van” service scenario, from needs research and business case through testing and handover to production.'],
 'task':['Проверить потребность в новом сервисном сценарии, сформировать предложение и подготовить продукт к запуску.','Validate demand for a new service scenario, define its value proposition and prepare the product for launch.'],
 'actions':[['Сформировал ценностное предложение, пользовательский путь и требования.','Defined the value proposition, user journey and requirements.'],['Подготовил модель спроса и unit-экономику, оценил условия масштабирования.','Built the demand model and unit economics, and assessed conditions for scaling.'],['Приоритизировал бэклог и координировал разработку, дизайн, аналитику и операционные команды.','Prioritised the backlog and coordinated engineering, design, analytics and operations.'],['Заложил систему метрик: спрос, конверсия, качество выполнения и повторное использование.','Established a metric system covering demand, conversion, fulfilment quality and repeat usage.']],
 'metrics':[['0 → 1',['путь от идеи до production','from idea to production']],['4',['направления продуктовых метрик','areas of product measurement']],['B2C',['новый сервисный сценарий','new service scenario']]],
 'closing':['В этом проекте важно было связать потребность пользователя, экономику сценария и его операционную реализацию.','This project brought together user needs, service economics and operational delivery.'],
 'steps':[['Потребность','Need'],['Бизнес-кейс','Business case'],['Запуск','Launch']]},
 {'slug':'gazprom','company':['Газпромнефть Бизнес-сервис','Gazpromneft Business Service'],'period':['Июль — сентябрь 2025','July — September 2025'],'type':['Enterprise / Исследования','Enterprise / Research'],
 'title':['Исследование AI-автоматизации в Газпромнефть Бизнес-сервис','AI automation research at Gazpromneft Business Service'],
 'short':['CustDev в 10 дочерних обществах, применение LLM и инструменты оценки эффекта роботизации.','CustDev across 10 subsidiaries, LLM applications and tools for evaluating automation impact.'],
 'role':['Руководитель проектов','Project Lead'],
 'intro':['Исследовал потребности внутренних пользователей, апробировал LLM для работы с документами и ERP, создавал инструменты оценки эффекта автоматизации.','Researched internal users’ needs, piloted LLMs for documents and ERP, and built tools for evaluating automation impact.'],
 'task':['Найти сценарии применения AI и роботизации во внутренних процессах и оценить их экономический смысл.','Identify AI and automation use cases in internal processes and assess their business value.'],
 'actions':[['Провёл CustDev с представителями 10 дочерних обществ.','Conducted CustDev with representatives of 10 subsidiaries.'],['Апробировал LLM для первичных учётных документов и ERP-систем.','Piloted LLMs for primary accounting documents and ERP systems.'],['Создал калькулятор и дашборды для оценки эффектов роботизации.','Built a calculator and dashboards to assess automation impact.'],['Усовершенствовал методологию инвестиционной оценки IT-решений и исследовал переход к продуктовому подходу.','Improved the investment appraisal methodology for IT solutions and researched a transition to a product approach.']],
 'metrics':[['10',['дочерних обществ в исследовании','subsidiaries in the research']],['LLM',['апробация на документах и ERP','pilots with documents and ERP']],['ROI',['калькулятор и дашборды эффектов','impact calculator and dashboards']]],
 'closing':['Продуктовая работа начинается с исследования процессов и понятной оценки эффекта — ещё до масштабирования технологии.','Product work starts with understanding processes and evaluating impact, before scaling the technology.'],
 'steps':[['Исследование','Research'],['Оценка эффекта','Impact assessment'],['Апробация','Pilot']]}
]
def v(pair): return pair[0 if LANG=='ru' else 1]
def structured_data(title, description, path):
 person_id=DOMAIN+'/#person'
 site_id=DOMAIN+'/#website'
 page_id=DOMAIN+path+'#webpage'
 person={'@type':'Person','@id':person_id,'name':t('Марк Сердюк','Mark Serdyuk'),'alternateName':t('Mark Serdyuk','Марк Сердюк'),'url':DOMAIN+'/','jobTitle':t('Продуктовый менеджер','Product Manager'),'sameAs':['https://t.me/serdukmark'],'worksFor':{'@type':'Organization','name':t('Магнит Tech','Magnit Tech')}}
 site={'@type':'WebSite','@id':site_id,'url':DOMAIN+'/','name':t('Марк Сердюк — портфолио','Mark Serdyuk — portfolio'),'inLanguage':['ru','en'],'publisher':{'@id':person_id}}
 page={'@type':'ProfilePage' if path==home() else 'WebPage','@id':page_id,'url':DOMAIN+path,'name':title,'description':description,'inLanguage':LANG,'isPartOf':{'@id':site_id},'about':{'@id':person_id}}
 graph=[site,person,page]
 if path==home():
  page['mainEntity']={'@id':person_id}
  page['hasPart']=[{'@id':DOMAIN+case_url(c['slug'])+'#project'} for c in CASES]
 else:
  c=next(c for c in CASES if case_url(c['slug'])==path)
  project_id=DOMAIN+path+'#project'
  breadcrumb_id=DOMAIN+path+'#breadcrumbs'
  page.update(mainEntity={'@id':project_id},breadcrumb={'@id':breadcrumb_id})
  graph += [{'@type':'CreativeWork','@id':project_id,'name':v(c['title']),'description':v(c['intro']),'url':DOMAIN+path,'inLanguage':LANG,'author':{'@id':person_id},'mainEntityOfPage':{'@id':page_id},'about':{'@type':'Organization','name':v(c['company'])}}, {'@type':'BreadcrumbList','@id':breadcrumb_id,'itemListElement':[{'@type':'ListItem','position':1,'name':t('Главная','Home'),'item':DOMAIN+home()},{'@type':'ListItem','position':2,'name':v(c['company']),'item':DOMAIN+path}]}]
 return json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('<','\\u003c')

def head(title,description,path,indexable=True):
 ru=path.removeprefix('/en') if path.startswith('/en/') else path
 en='/en'+ru
 discovery=(f'<link rel="canonical" href="{DOMAIN}{path}"><link rel="alternate" hreflang="ru" href="{DOMAIN}{ru}"><link rel="alternate" hreflang="en" href="{DOMAIN}{en}"><link rel="alternate" hreflang="x-default" href="{DOMAIN}{ru}"><meta name="robots" content="index, follow, max-image-preview:large">' if indexable else '<meta name="robots" content="noindex, follow">')
 schema=f'<script type="application/ld+json">{structured_data(title,description,path)}</script>' if indexable else ''
 return f'''<!doctype html>
<html lang="{LANG}" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{label(title)}</title><meta name="description" content="{label(description)}"><meta name="author" content="{t('Марк Сердюк','Mark Serdyuk')}">
{discovery}
<meta name="theme-color" content="#111210" id="theme-color"><meta property="og:type" content="website"><meta property="og:title" content="{label(title)}"><meta property="og:description" content="{label(description)}"><meta property="og:url" content="{DOMAIN}{path}"><meta property="og:image" content="{DOMAIN}/assets/img/social-cover.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="{t('Марк Сердюк — AI-продукты и B2B-платформы','Mark Serdyuk — AI products and B2B platforms')}"><meta property="og:locale" content="{t('ru_RU','en_US')}"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.ico" sizes="any"><link rel="apple-touch-icon" href="/icon_for_sait.png"><link rel="alternate" type="application/atom+xml" title="{t('Обновления Марка Сердюка','Mark Serdyuk updates')}" href="{home()}feed.xml">
<link rel="preload" href="/assets/fonts/unbounded-{t('cyrillic','latin')}.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/inter-{t('cyrillic','latin')}.woff2" as="font" type="font/woff2" crossorigin>
<script>try{{document.documentElement.dataset.theme=localStorage.getItem('theme')==='light'?'light':'dark';document.querySelector('#theme-color').content=document.documentElement.dataset.theme==='light'?'#f4f1e9':'#111210'}}catch(e){{}}</script>
<link rel="stylesheet" href="{asset('assets/styles.css')}"><script src="{asset('assets/config.js')}" defer></script><script src="{asset('assets/app.js')}" data-game-src="{asset('assets/game.js')}" defer></script>
{schema}</head><body>
<a class="skip-link" href="#main">{t('К содержимому','Skip to content')}</a>'''
def header(path):
 alt=('/en'+path) if LANG=='ru' else path.removeprefix('/en')
 nav=''.join(link(home()+'#'+anchor,text) for anchor,text in [('work',t('Проекты','Work')),('approach',t('Подход','Approach')),('now',t('Сейчас','Now')),('about',t('Обо мне','About'))])
 return f'''<header class="site-header"><div class="wrap header-inner"><a class="brand" href="{home()}" aria-label="{t('Марк Сердюк — главная','Mark Serdyuk — home')}">ms<span>.</span></a><nav class="desktop-nav" aria-label="{t('Главная навигация','Main navigation')}">{nav}</nav><div class="header-tools"><a class="lang-link" href="{alt}" hreflang="{t('en','ru')}" lang="{t('en','ru')}" aria-label="{t('English version','Русская версия')}">{t('EN','RU')}</a><button class="theme-toggle icon-button" aria-label="{t('Включить светлую тему','Switch to light theme')}" aria-pressed="false"><span aria-hidden="true" class="theme-icon">☀</span></button><a class="header-contact" href="{home()}#contact">{t('На связи','Let’s talk')} {ARROW}</a><button class="menu-button icon-button" aria-controls="mobile-nav" aria-expanded="false" aria-label="{t('Открыть меню','Open menu')}"><span aria-hidden="true">☰</span></button></div></div><nav id="mobile-nav" class="mobile-nav wrap" aria-label="{t('Мобильная навигация','Mobile navigation')}" hidden>{nav}{link(home()+'#contact',t('Контакты','Contact'))}</nav></header>'''
def section_head(n,kicker,title,extra=''):
 return f'<div class="section-head"><div class="eyebrow"><span>{n}</span> {kicker}</div><div class="section-title"><h2>{title}</h2>{extra}</div></div>'
def footer():
 return f'''<footer class="wrap footer"><a class="brand" href="{home()}">ms<span>.</span></a><span>© {date.today().year} {t('Марк Сердюк','Mark Serdyuk')}</span><a href="{home()}feed.xml">RSS ↗</a><a href="#top">{t('Наверх','Back to top')} ↑</a></footer><div class="toast" role="status" aria-live="polite" id="toast"></div></body></html>'''
def contact():
 return f'''<section class="contact-section" id="contact"><div class="wrap contact-inner"><div><p class="eyebrow">{t('Следующий разговор','The next conversation')}</p><h2>{t('Хорошие продукты<br> начинаются<br> с <em>разговора.</em>','Good products<br> start with a<br> <em>conversation.</em>')}</h2><p>{t('О продуктовой роли, AI-задаче или просто о том, что нового.','A product role, an AI challenge, or simply a catch-up.')}</p></div><div class="contact-links">{cta(t('Написать мне','Say hello'))}<a href="mailto:m.gov@internet.ru" data-track="email_click">m.gov@internet.ru {ARROW}</a><a href="tel:+79529977440" data-track="phone_click">+7 952 997-74-40 {ARROW}</a><button class="copy-contact text-link" data-copy="m.gov@internet.ru">{t('Скопировать email','Copy email')} ⧉</button><div class="contact-cv">{cv()}<span>{t('Полный опыт и проекты','Full experience and projects')}</span></div><p class="reply-note">{t('Отвечаю в течение дня','I reply within a day')}</p></div></div></section>'''
def diagram(c,large=False):
 return f'''<div class="project-art art-{c['slug']} {'large' if large else ''}" aria-hidden="true"><div class="art-grid"></div><span class="art-index">{ {'magnit':'01 / AI','yandex':'02 / LAUNCH','gazprom':'03 / DISCOVERY'}[c['slug']]}</span><div class="flow">{''.join(f'<span class="flow-node node-{i}"><i>{["↗","✳","↗"][i]}</i><b>{v(s)}</b></span>'+('<span class="flow-line"></span>' if i<2 else '') for i,s in enumerate(c['steps']))}</div><span class="art-caption">{t('Схема подхода','An outline of the approach')}</span></div>'''
def projects():
 cards=''
 for i,c in enumerate(CASES):
  cards+=f'''<article class="project-card {'featured' if i==0 else ''}"><a href="{case_url(c['slug'])}" data-track="case_open" data-project="{c['slug']}" class="project-link">{diagram(c)}<div class="project-body"><div class="project-meta"><span>{v(c['company'])}</span><span>{v(c['type'])}</span></div><h3>{v(c['title'])}</h3><p>{v(c['short'])}</p><div class="project-bottom"><span>{t('О проекте','Explore project')}</span>{ARROW}</div></div></a></article>'''
 return f'''<section class="section wrap" id="work">{section_head('01',t('Избранные проекты','Selected work'),t('От вопроса<br> к результату.','From a question<br> to a result.'),f'<p>{t("Три проекта, которые лучше всего<br> показывают мой подход к работе.","Three projects that best<br> represent the way I work.")}</p>')}<div class="projects-grid">{cards}</div></section>'''
def calculator():
 inputs=[('people',t('Пользователей','Users'),10,2000,100,10),('minutes',t('Минут экономии в день','Minutes saved per day'),5,120,20,5),('cost',t('Стоимость часа, ₽','Hourly cost, RUB'),200,5000,1000,100),('adoption',t('Доля использования, %','Adoption rate, %'),10,100,60,5)]
 fields=''.join(f'<div class="calc-field"><div><label for="{k}">{txt}</label><output for="{k}" id="{k}-value">{value}</output></div><input id="{k}" name="{k}" type="range" min="{lo}" max="{hi}" value="{value}" step="{step}"></div>' for k,txt,lo,hi,value,step in inputs)
 return f'''<section class="lab-section" id="lab"><div class="wrap lab-grid"><div><p class="eyebrow">{t('Небольшой эксперимент','A small experiment')} / 01</p><h2>{t('Сколько стоит<br> <em>сэкономленное<br> время?</em>','What is<br> <em>saved time<br> worth?</em>')}</h2><p>{t('Подвигай ползунки и оцени потенциал AI-автоматизации для команды.','Move the sliders to explore the potential of AI automation for a team.')}</p><p class="lab-note">{t('Иллюстративная модель, не расчёт какого-либо из моих проектов.','An illustrative model, not a calculation for any of my projects.')}</p></div><div class="calculator"><div class="calc-heading"><span>{t('Потенциал автоматизации','Automation potential')}</span><span aria-hidden="true">↗</span></div><div class="calc-fields">{fields}</div><div class="calc-result" role="status" aria-live="polite" aria-atomic="true"><span>{t('Стоимость высвобождённого времени за год','Annual value of time freed up')}</span><strong id="calc-result">4,8 <small>{t('млн ₽','M RUB')}</small></strong><p id="calc-hours">{t('4 800 часов в год','4,800 hours per year')}</p></div><details class="calc-method"><summary>{t('Как считается и что не учтено','Method and limitations')}</summary><p>{t('Пользователи × минуты / 60 × стоимость часа × 240 рабочих дней × доля использования.','Users × minutes / 60 × hourly cost × 240 working days × adoption rate.')}</p><p>{t('Это оценка стоимости времени, а не обещанная экономия бюджета. Затраты на внедрение, модели, поддержку и проверку качества не вычтены.','This estimates the value of time, not guaranteed budget savings. Implementation, model, support and quality assurance costs have not been deducted.')}</p></details><noscript><p>{t('Для изменения параметров включите JavaScript.','Enable JavaScript to adjust the inputs.')}</p></noscript></div></div></section>'''
def updates():
 entries=json.loads((ROOT/'content/updates.json').read_text())
 rows=''.join(f'<li><time>{v(e["period"])}</time><div><span class="update-tag">{v(e["tag"])}</span><h3>{v(e["title"])}</h3><p>{v(e["text"])}</p></div></li>' for e in entries)
 return f'''<section class="section wrap" id="now">{section_head('03',t('Сейчас и по пути','Now and along the way'),t('Продолжаю<br> двигаться.','Still<br> moving forward.'),link(home()+'feed.xml',t('Следить через RSS ↗','Follow via RSS ↗'),'text-link'))}<div class="now-grid"><div class="now-card"><div class="eyebrow"><span class="status-dot"></span>{t('В фокусе','Current focus')}</div><h3>{t('AI-продукты<br> в Магнит Tech.','AI products<br> at Magnit Tech.')}</h3><p>{t('Развиваю внутренние платформы, внедряю AI в рабочие процессы и учу команды им пользоваться.','Developing internal platforms, bringing AI into workflows and helping teams use it.')}</p><div class="now-foot">{t('Москва · сентябрь 2026','Moscow · September 2026')}<span aria-hidden="true">↗</span></div></div><ol class="updates">{rows}</ol></div></section>'''
def about():
 rows=[('2024—2028',t('Центральный университет','Central University'),t('Математика и компьютерные науки · продуктовый менеджмент.','Mathematics and Computer Science · Product Management.')),('2025—2026',t('Преподавание бизнес-аналитики','Teaching business analytics'),t('100+ проверенных кейсов, занятия для аудиторий до 170 студентов.','100+ cases reviewed, classes for audiences of up to 170 students.')),('2025',t('Корпоративный университет Газпром нефти','Gazprom Neft Corporate University'),t('Программа для руководителей проектов и продуктовых команд.','A programme for project leads and product teams.'))]
 awards=[('7',t('стипендий','scholarships'),t('Потанин, Т-Банк, Центральный университет, Avito, Сбер, Reksoft Consulting, Московская биржа.','Potanin Foundation, T-Bank, Central University, Avito, Sber, Reksoft Consulting, Moscow Exchange.')),('3',t('призовых результата на хакатонах','hackathon wins and podium finishes'),t('AI&Business SPB, «Идея. Код. Релиз.», Datathon 2.0.','AI&Business SPB, “Idea. Code. Release.”, Datathon 2.0.')),('↗',t('финалист и ментор DEADLINE','DEADLINE finalist and mentor'),t('От финала 2024 года — к менторству команд-призёров в 2025–2026.','From the 2024 final to mentoring podium teams in 2025–2026.'))]
 others=[(t('Т-Банк','T-Bank'),t('131 глубинное интервью с автосервисами, партнёрская база для 5 регионов и лендинг привлечения.','131 in-depth interviews with auto services, a partner pipeline for 5 regions and an acquisition landing page.')),(t('X5 Group','X5 Group'),t('Полевые исследования в 9 регионах, CJM и 50+ предложений по системе полномочий директоров-партнёров.','Field research across 9 regions, a CJM and 50+ proposals for the partner directors’ authority system.')),(t('Стратегия образования до 2040 года','National Education Strategy 2040'),t('Руководил рабочей группой из 8 человек, собрал позиции 100+ экспертов и представлял результаты органам власти.','Led a working group of 8, gathered input from 100+ experts and presented the results to government bodies.')),(t('Исследования и БРИКС','Research and BRICS'),t('Аналитика по розничным инвесторам стран БРИКС и предложение по трансформации платежей; доклад представлен в Бразилии в мае 2025 года.','Research on retail investors in BRICS countries and a payment transformation proposal, presented in Brazil in May 2025.'))]
 return f'''<section class="section wrap" id="about">{section_head('04',t('Человек за проектами','The person behind the work'),t('Любопытство —<br> тоже навык.','Curiosity is<br> a skill, too.'))}<div class="about-grid"><div class="about-lead"><p>{t('Я Марк. Мне интересно разбираться в сложном, собирать из этого работающие продукты и делиться тем, что понял.','I’m Mark. I enjoy making sense of complex problems, turning that understanding into working products and sharing what I learn.')}</p><p>{t('Кроме продуктовой работы — преподавание, фортепиано, спорт и генеративное искусство. Создал выставку CU:/dev/art и основал студенческий спортивный клуб.','Beyond product work: teaching, piano, sport and generative art. I created the CU:/dev/art exhibition and founded a student sports club.')}</p><p class="aside-note">{t('Параллельно пробую себя в предпринимательстве: развиваю GenAI-проект в индустрии красоты.','Alongside my product career, I explore entrepreneurship through a GenAI project in the beauty industry.')}</p><div class="personal-tags"><span>CU:/dev/art</span><span>{t('4 премии за фортепиано','4 piano awards')}</span><span>{t('Спорт и сообщество','Sport & community')}</span></div></div><div class="education">{''.join(f'<div class="education-row"><span>{year}</span><h3>{name}</h3><p>{desc}</p></div>' for year,name,desc in rows)}</div></div><div class="awards-grid">{''.join(f'<article><strong>{num}</strong><h3>{title}</h3><p>{desc}</p></article>' for num,title,desc in awards)}</div><details class="more-experience"><summary>{t('Ещё проекты и исследования','More projects and research')}<span aria-hidden="true">+</span></summary><div class="other-projects">{''.join(f'<article><h3>{company}</h3><p>{txt}</p></article>' for company,txt in others)}</div></details></section>'''
def faq():
 rows=[
  (t('Чем занимается Марк Сердюк?','What does Mark Serdyuk do?'),t('Я продуктовый менеджер: развиваю AI-продукты, B2B-платформы и внутренние сервисы. Сейчас работаю в Магнит Tech; до этого запускал сервисный сценарий в Яндексе и исследовал автоматизацию в Газпромнефть Бизнес-сервис.','I am a Product Manager working on AI products, B2B platforms and internal services. I currently work at Magnit Tech; previously, I launched a service scenario at Yandex and researched automation at Gazpromneft Business Service.')),
  (t('Какой у меня опыт внедрения AI?','What is my experience with AI adoption?'),t('В Магнит Tech создал и запустил мультиагентного AI-ассистента для более 700 еженедельных пользователей на руководящих позициях. Также обучил работе с AI более 150 продактов и тимлидов.','At Magnit Tech, I built and launched a multi-agent AI assistant with over 700 weekly users in leadership roles. I also trained more than 150 product managers and team leads in AI tools.')+' '+link(case_url('magnit'),t('Подробнее о проекте.','Read about the project.'))),
  (t('Где посмотреть проекты и резюме?','Where can I find projects and my CV?'),t('На сайте — три проекта с описанием задачи, моей роли и результата. Полный опыт собран в резюме на русском языке.','The site presents three projects with their challenges, my role and outcomes. My full experience is available in the Russian-language CV.')+' '+link(home()+'#work',t('Проекты','Projects'))+' · '+cv()),
  (t('Как связаться и следить за обновлениями?','How can you contact me and follow updates?'),t('Обсудить продуктовую роль или AI-задачу можно в Telegram. Новые вехи публикую в разделе «Сейчас»; подписаться на них можно через RSS.','You can contact me on Telegram to discuss a product role or an AI challenge. I share milestones in the Now section, with an RSS feed for updates.')+' '+link('https://t.me/serdukmark','Telegram',extra='data-track="telegram_click"')+' · '+link(home()+'feed.xml','RSS'))
 ]
 return f'<section class="section wrap faq" id="faq">{section_head("05",t("Коротко о главном","At a glance"),t("Вопросы и ответы","Questions and answers"))}<div class="faq-list">'+''.join(f'<article><h3>{q}</h3><p>{a}</p></article>' for q,a in rows)+'</div></section>'

def game():
 return f'''<section class="wrap easter-egg" id="game"><details id="game-details"><summary><span>✳ <b>PM Runner</b> <span class="muted">{t('Маленький перерыв между спринтами','A little break between sprints')}</span></span><span aria-hidden="true">+</span></summary><div class="game-content"><p>{t('Прыгай через баги и дедлайны. Пробел, ↑ или тап — прыжок. Можно прыгнуть дважды. Кофе — +10 очков.','Jump over bugs and deadlines. Space, ↑ or tap to jump. Double jump is available. Coffee adds 10 points.')}</p><div class="game__layout"><div><div class="game__hud"><span>{t('Очки','Score')}: <b id="g-score">0</b></span><span>{t('Рекорд','Best')}: <b id="g-hi">0</b></span><span id="g-speed">{t('Скорость: нормальная','Speed: normal')}</span><button id="g-pause" class="text-link" hidden>{t('Пауза','Pause')}</button></div><div class="game__stage"><canvas id="g-canvas" width="700" height="200" tabindex="0" aria-label="{t('PM Runner. Пробел или стрелка вверх — прыжок. Escape — пауза.','PM Runner. Space or Up to jump. Escape to pause.')}"></canvas><div class="game__overlay" id="g-overlay"><p class="game__title">PM Runner</p><button class="button primary" id="g-start">{t('Запустить спринт','Start sprint')}</button></div></div><p id="g-status" class="game-status" role="status" aria-live="polite"></p></div><aside class="board"><h3>{t('Топ игроков','Top players')}</h3><div id="lb-list"><p>{t('Рейтинг загрузится при открытии игры.','The leaderboard loads when you open the game.')}</p></div></aside></div><noscript>{t('Для игры нужен JavaScript.','The game requires JavaScript.')}</noscript></div></details></section>'''
def homepage():
 title=t('Марк Сердюк — продуктовый менеджер AI и B2B','Mark Serdyuk — AI & B2B Product Manager')
 description=t('Продуктовый менеджер в Магнит Tech. AI-ассистенты, запуск сервисов и внутренние платформы. Проекты, подход к работе и новые вехи.','Product Manager at Magnit Tech. AI assistants, service launches and internal platforms. Selected work, my approach and milestones.')
 result=head(title,description,home())+header(home())
 result+=f'''<main id="main"><div id="top"></div><section class="hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span>{t('Марк Сердюк','Mark Serdyuk')}<span class="eyebrow-separator">/</span>Product Manager</div><h1>{t('От идеи —<br> к работающему<br> <em>продукту.</em>','From an idea<br> to a product<br> <em>that works.</em>')}</h1><p class="hero-lead">{t('Я Марк Сердюк, продуктовый менеджер.<br> Создаю AI-продукты и B2B-платформы.<br> Соединяю исследование, технологии<br> и измеримый бизнес-эффект.','I’m Mark Serdyuk, a Product Manager.<br> I build AI products and B2B platforms.<br> Connecting research, technology<br> and measurable business impact.')}</p><div class="hero-actions">{link('#work',t('Смотреть проекты','Explore my work')+' '+ARROW,'button primary')}{cta(t('Связаться','Get in touch'))}{cv()}</div><div class="hero-stats"><div><strong>100 <small>{t('млн ₽','M RUB')}</small></strong><span>{t('экономический эффект / год','economic impact / year')}</span></div><div><strong>700<span>+</span></strong><span>{t('руководителей используют AI еженедельно','leaders use the AI assistant weekly')}</span></div></div></div><figure class="hero-portrait"><img src="/assets/img/mark-portrait-960.webp" srcset="/assets/img/mark-portrait-480.webp 480w, /assets/img/mark-portrait-960.webp 960w" sizes="(max-width: 700px) 180px, (max-width: 1050px) 35vw, 420px" width="1122" height="1402" alt="{t('Марк Сердюк — стилизованный AI-портрет','Mark Serdyuk — a stylised AI portrait')}" fetchpriority="high"><div class="portrait-status"><span class="status-dot"></span><div><strong>{t('Сейчас — Магнит Tech','Currently at Magnit Tech')}</strong><span>{t('AI-продукты и внутренние платформы','AI products & internal platforms')}</span></div>{ARROW}</div><figcaption>{t('Немного AI — даже в портрете.','A little AI — even in the portrait.')}</figcaption></figure></section><div class="wrap companies"><p>{t('Опыт и проектная работа','Experience & project work')}</p><div><span>{t('Магнит Tech','Magnit Tech')}</span><span>{t('Яндекс','Yandex')}</span><span>{t('Газпром нефть','Gazprom Neft')}</span><span>{t('Т-Банк','T-Bank')}</span><span>X5 Group</span></div></div>'''
 result+=projects()
 steps=[('01',t('Разобраться','Understand'),t('Потребность, контекст, ограничения. Интервью и данные до выбора решения.','Needs, context, constraints. Interviews and data before choosing a solution.')),('02',t('Посчитать','Evaluate'),t('Ценность, продуктовые метрики и экономика. Понятные критерии результата.','Value, product metrics and economics. Clear criteria for success.')),('03',t('Запустить','Launch'),t('Приоритеты, требования и работа с командой. От гипотезы до использования.','Priorities, requirements and teamwork. From a hypothesis to real use.')),('04',t('Развивать','Improve'),t('Обратная связь, измерение эффекта и следующие итерации продукта.','Feedback, impact measurement and the next product iterations.'))]
 result+=f'''<section class="section wrap approach" id="approach">{section_head('02',t('Как я работаю','How I work'),t('Сначала смысл.<br> Потом — решение.','Understand the why.<br> Then build the how.'))}<div class="approach-grid">{''.join(f'<article><span>{num}</span><h3>{name}</h3><p>{desc}</p></article>' for num,name,desc in steps)}</div><div class="toolkit"><span>{t('В работе','My toolkit')}</span><p>CustDev · JTBD · CJM · Unit economics · SQL · LLM · {t('Мультиагентные системы','Multi-agent systems')} · A/B tests</p></div></section>'''
 result+=calculator()+updates()+about()+faq()+contact()+game()+'</main>'+footer()
 return result

def casepage(c):
 path=case_url(c['slug'])
 result=head(v(c['title'])+' — '+t('Марк Сердюк','Mark Serdyuk'),v(c['intro']),path)+header(path)
 result+=f'''<main id="main"><div id="top"></div><article class="wrap case-page"><nav class="breadcrumbs" aria-label="{t('Хлебные крошки','Breadcrumb')}"><a href="{home()}">{t('Главная','Home')}</a><span aria-hidden="true">/</span><span aria-current="page">{v(c['company'])}</span></nav><a class="text-link back-link" href="{home()}#work">← {t('Все проекты','All projects')}</a><div class="eyebrow">{v(c['company'])} / {v(c['type'])}</div><h1>{v(c['title'])}</h1><p class="case-intro">{v(c['intro'])}</p><div class="case-meta"><div><span>{t('Роль','Role')}</span><strong>{v(c['role'])}</strong></div><div><span>{t('Период','Period')}</span><strong>{v(c['period'])}</strong></div></div>{diagram(c,True)}<div class="case-stats">{''.join(f'<div><strong>{num}</strong><span>{v(txt)}</span></div>' for num,txt in c['metrics'])}</div><div class="case-section"><h2>{t('Задача','The challenge')}</h2><p>{v(c['task'])}</p></div><div class="case-section"><h2>{t('Что я сделал','My contribution')}</h2><ol>{''.join(f'<li>{v(a)}</li>' for a in c['actions'])}</ol></div><div class="case-takeaway"><p class="eyebrow">{t('Мой взгляд','My perspective')}</p><p>{v(c['closing'])}</p></div><div class="next-projects"><h2>{t('Другие проекты','More work')}</h2>{''.join(link(case_url(other['slug']),v(other['company'])+' '+ARROW,'next-project') for other in CASES if other!=c)}</div></article>{contact()}</main>{footer()}'''
 return result

def write(path,content):
 target=ROOT/path.lstrip('/')
 if path.endswith('/'): target=target/'index.html'
 target.parent.mkdir(parents=True,exist_ok=True);target.write_text(content,encoding='utf-8')
def feeds():
 entries=json.loads((ROOT/'content/updates.json').read_text())
 xml=f'<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom" xml:lang="{LANG}"><title>{t("Марк Сердюк — обновления","Mark Serdyuk — updates")}</title><id>{DOMAIN}{home()}feed.xml</id><link href="{DOMAIN}{home()}feed.xml" rel="self"/><link href="{DOMAIN}{home()}#now"/><updated>2026-09-23T00:00:00Z</updated><author><name>{t("Марк Сердюк","Mark Serdyuk")}</name></author>'
 for e in entries:
  xml+=f'<entry><id>{DOMAIN}/milestones/{e["id"]}</id><title>{esc(v(e["title"]))}</title><link href="{DOMAIN}{home()}#now"/><updated>2026-09-23T00:00:00Z</updated><summary>{esc(v(e["period"])+". "+v(e["text"]))}</summary></entry>'
 write(home()+'feed.xml',xml+'</feed>')
if __name__=='__main__':
 paths=[]
 for LANG in ('ru','en'):
  write(home(),homepage());paths.append(home())
  for c in CASES: write(case_url(c['slug']),casepage(c));paths.append(case_url(c['slug']))
  feeds()
 write('/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{DOMAIN}{p}</loc></url>' for p in paths)+'</urlset>')
 LANG='ru'
 write('/404.html',head('Страница не найдена · Page not found','Марк Сердюк — портфолио','/404.html',indexable=False)+header('/')+'<main id="main" class="wrap not-found"><div id="top"></div><p class="eyebrow">404 / LOST IN DISCOVERY</p><h1>Кажется, здесь<br> пока гипотеза.</h1><p>Такой страницы нет. / This page does not exist.</p><a class="button primary" href="/">На главную →</a><a class="text-link" href="/en/">English home →</a></main>'+footer())
 print('Built',len(paths),'pages, two feeds, sitemap and 404.')
